---
- name: add repo
  apt_repository: repo="ppa:adiscon/{{rsyslog_repo_version}}"
  when: ansible_distribution == 'Ubuntu'

- name: add key
  apt_key: keyserver=keys.gnupg.net id=AEF0CF8E
  when: ansible_distribution == 'Debian'

- name: add repo
  apt_repository: repo="{{item}}/{{rsyslog_repo_version}} {{ansible_distribution_release}}"
  with_items:
    - "deb http://debian.adiscon.com/"
    - "deb-src http://debian.adiscon.com/"
  when: ansible_distribution == 'Debian'

- name: add rsyslog
  apt: name=rsyslog state=present
